include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - avoid_print
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_typing_uninitialized_variables
    - use_key_in_widget_constructors
    - prefer_final_fields
    - unnecessary_brace_in_string_interps
    - unnecessary_string_interpolations